AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  3BCDXPAppointmentSyncP2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 10240
      Timeout: 900
      Role: >-
        arn:aws:iam::570277181188:role/service-role/fetch_CVH_clients-role-pk5n92fz
