AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  sendpayloadsqsv2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: >-
        arn:aws:iam::570277181188:role/service-role/fetch_CVH_clients-role-pk5n92fz
      VpcConfig:
        SecurityGroupIds:
          - sg-0412baeb8b49885f3
          - sg-0a62369466bd6dbdc
        SubnetIds:
          - subnet-050a368a85c138678
